[workspace.package]
version = "0.1.3"
description = "EGM96 altitude above WGS84 Ellipsoid"
edition = "2021"
license = "Zlib"
homepage = "https://github.com/micahcc/egm96-rs"

[workspace]
resolver = "2"
members = ["egm96", "egm96-c"]
