[package]
name = "egm96"
version = "0.1.1"
edition = "2021"
description = "EGM96 altitude above WGS84 Ellipsoid"
license = "zlib"
license-file = "LICENSE"
homepage = "https://github.com/micahcc/egm96-rs"
